# Development Docker Compose configuration
# Use with: docker-compose -f docker-compose.yml -f docker-compose.dev.yml up

services:
  random-server:
    # Override build for development
    build:
      context: .
      dockerfile: Dockerfile
      target: builder  # Stop at builder stage for development
    
    # Development environment variables
    environment:
      - LOG_LEVEL=DEBUG
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
    
    # Mount source code for live reloading
    volumes:
      - ./src:/app/src:ro
      - ./tests:/app/tests:ro
      - ./pyproject.toml:/app/pyproject.toml:ro
      - ./uv.lock:/app/uv.lock:ro
    
    # Override command for development
    command: ["uv", "run", "--frozen", "--reload", "src/random_server.py"]